export const API = 'API';
export const SET_USER_INFO = 'SET_USER_INFO';
export const RESET_USER_INFO = 'RESET_USER_INFO';
export const FETCH_PRONTUARIOS = 'FETCH_PRONTUARIOS';
export const EDIT_PRONTUARIO = 'EDIT_PRONTUARIO';
